#!/bin/bash

version=$1

if [ -z "$version" ]; then
   echo "*** usage: make-release-tarball version"
   echo "       version is like 11.5, etc."
   exit 1
fi

mv sched sched_${version}

tar --exclude=".svn" --exclude="*.o" --exclude="*~" --exclude="lib" \
    --exclude="core*" --exclude="TEST" --exclude="RELATED_CODE" \
    --exclude=".cvsignore" --exclude="*.out" --exclude=".DS*" \
    --exclude="*.tgz" \
    -czf sched_${version}.tgz sched_${version}

mv sched_${version} sched
